const axios = require('axios');
const OpenAI = require('openai');
const { CallRecord } = require('../models');

class AIService {
    constructor() {
        // For open-source alternatives, we'll use a configurable approach
        // that can work with local models or API-compatible services
        this.openai = null;

        if (process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY !== 'your_openai_api_key_here') {
            this.openai = new OpenAI({
                apiKey: process.env.OPENAI_API_KEY,
            });
        }
    }

    /**
     * Generate a dynamic call script based on lead information
     */
    async generateCallScript(leadData, callPurpose = 'initial_contact') {
        try {
            const prompt = this.buildScriptPrompt(leadData, callPurpose);

            if (this.openai) {
                // Use OpenAI API
                const response = await this.openai.createChatCompletion({
                    model: process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
                    messages: [{ role: 'user', content: prompt }],
                    max_tokens: 300,
                    temperature: 0.7
                });

                return response.data.choices[0].message.content.trim();
            } else {
                // Fallback to a simulated response or local model
                // In a real implementation, this would connect to a local model
                return this.generateLocalScript(prompt, leadData, callPurpose);
            }
        } catch (error) {
            console.error('Error generating call script:', error);
            throw new Error('Failed to generate call script');
        }
    }

    /**
     * Build a prompt for script generation
     */
    buildScriptPrompt(leadData, purpose) {
        let purposeText = '';
        switch (purpose) {
            case 'initial_contact':
                purposeText = 'introduce our product/service and schedule a follow-up meeting';
                break;
            case 'follow_up':
                purposeText = 'follow up on a previous conversation and address concerns';
                break;
            case 'product_demo':
                purposeText = 'offer a product demonstration and answer questions';
                break;
            default:
                purposeText = 'engage in a professional conversation';
        }

        return `Generate a professional sales call script for a lead named ${leadData.name || 'prospect'}.
    Company: ${leadData.company || 'not provided'}
    Email: ${leadData.email || 'not provided'}
    Phone: ${leadData.phone || 'not provided'}
    
    The purpose of this call is to ${purposeText}. 
    Include:
    1. A warm greeting and introduction
    2. A brief mention of our solution
    3. Questions to qualify the lead
    4. A clear call-to-action
    
    Keep the script conversational and natural.`;
    }

    /**
     * Generate script using local logic (fallback)
     */
    generateLocalScript(prompt, leadData, purpose) {
        // This is a simplified fallback - in a real implementation,
        // this would connect to local models like Ollama, Hugging Face, etc.
        return `Hello ${leadData.name || 'there'}, this is an AI-generated script.
    Purpose: ${purpose}
    
    This is a placeholder for the actual AI-generated script.
    In a production environment, this would be replaced with an actual script
    generated by an open-source AI model like LLaMA, Mistral, or similar.`;
    }

    /**
     * Generate conversational responses during a call
     */
    async generateResponse(userInput, context = {}) {
        try {
            const prompt = `Based on the following conversation context and user input, generate an appropriate response:
      
      Context: ${JSON.stringify(context)}
      User Input: "${userInput}"
      
      Generate a helpful, professional response that addresses the user's concern or continues the conversation appropriately.`;

            if (this.openai) {
                const response = await this.openai.createChatCompletion({
                    model: process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
                    messages: [{ role: 'user', content: prompt }],
                    max_tokens: 150,
                    temperature: 0.6
                });

                return response.data.choices[0].message.content.trim();
            } else {
                return this.generateLocalResponse(prompt, userInput, context);
            }
        } catch (error) {
            console.error('Error generating response:', error);
            throw new Error('Failed to generate AI response');
        }
    }

    generateLocalResponse(prompt, userInput, context) {
        return `This is a placeholder response for: "${userInput}". 
    In a production environment, this would be an AI-generated response.`;
    }

    /**
     * Summarize a call transcript
     */
    async summarizeTranscript(transcript) {
        try {
            const prompt = `Please provide a concise summary of the following call transcript:
      
      ${transcript}
      
      The summary should include:
      1. Key topics discussed
      2. Main outcomes or decisions
      3. Action items or next steps
      4. Overall sentiment of the conversation
      
      Limit the summary to 100-150 words.`;

            if (this.openai) {
                const response = await this.openai.createChatCompletion({
                    model: process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
                    messages: [{ role: 'user', content: prompt }],
                    max_tokens: 200,
                    temperature: 0.3
                });

                return response.data.choices[0].message.content.trim();
            } else {
                return this.generateLocalSummary(prompt, transcript);
            }
        } catch (error) {
            console.error('Error summarizing transcript:', error);
            throw new Error('Failed to summarize transcript');
        }
    }

    generateLocalSummary(prompt, transcript) {
        return `This is a placeholder summary of the call transcript.
    In a production environment, this would be an AI-generated summary of:
    - Key discussion points
    - Outcomes/decisions
    - Action items
    - Sentiment analysis`;
    }

    /**
     * Analyze sentiment of text
     */
    async analyzeSentiment(text) {
        try {
            const prompt = `Analyze the sentiment of the following text and provide a score between -1 and 1:
      -1 being very negative
       0 being neutral
       1 being very positive
      
      Text: "${text}"
      
      Respond with only the numeric score between -1 and 1.`;

            if (this.openai) {
                const response = await this.openai.createChatCompletion({
                    model: process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
                    messages: [{ role: 'user', content: prompt }],
                    max_tokens: 10,
                    temperature: 0.1
                });

                const score = parseFloat(response.data.choices[0].message.content.trim());
                return Math.max(-1, Math.min(1, score)); // Clamp between -1 and 1
            } else {
                return this.analyzeLocalSentiment(prompt, text);
            }
        } catch (error) {
            console.error('Error analyzing sentiment:', error);
            throw new Error('Failed to analyze sentiment');
        }
    }

    analyzeLocalSentiment(prompt, text) {
        // Simple heuristic for demo purposes
        const positiveWords = ['good', 'great', 'excellent', 'amazing', 'wonderful', 'love', 'perfect', 'fantastic'];
        const negativeWords = ['bad', 'terrible', 'awful', 'hate', 'horrible', 'disappointed', 'worst', 'poor'];

        const textLower = text.toLowerCase();
        const words = textLower.split(/\s+/);

        let positiveCount = 0;
        let negativeCount = 0;

        words.forEach(word => {
            if (positiveWords.some(posWord => word.includes(posWord))) positiveCount++;
            if (negativeWords.some(negWord => word.includes(negWord))) negativeCount++;
        });

        if (positiveCount === 0 && negativeCount === 0) return 0.1; // Slightly positive by default
        if (positiveCount === 0 && negativeCount > 0) return -0.5;
        if (positiveCount > 0 && negativeCount === 0) return 0.5;

        const ratio = (positiveCount - negativeCount) / (positiveCount + negativeCount);
        return Math.max(-1, Math.min(1, ratio));
    }

    /**
     * Process call recording for transcription
     * Note: In a real implementation, this would interface with Whisper or similar
     */
    async transcribeAudio(audioFilePath) {
        try {
            // In a real implementation, this would:
            // 1. Upload the audio file to a service like OpenAI's Whisper API
            // 2. Or use a local Whisper model
            // 3. Or use another speech-to-text service

            // Placeholder for audio transcription
            return {
                text: "This is a placeholder transcript. In a real implementation, this would be the actual transcription of the audio file.",
                segments: [] // Detailed timing information would go here
            };
        } catch (error) {
            console.error('Error transcribing audio:', error);
            throw new Error('Failed to transcribe audio');
        }
    }
}

module.exports = new AIService();